package com.example.tourism.database.dao;

import com.example.tourism.database.bean.ContactsBean;
import com.example.tourism.database.bean.SeachContent;
import com.example.tourism.database.bean.TripBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsBeanDaoConfig;
    private final DaoConfig seachContentDaoConfig;
    private final DaoConfig tripBeanDaoConfig;

    private final ContactsBeanDao contactsBeanDao;
    private final SeachContentDao seachContentDao;
    private final TripBeanDao tripBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsBeanDaoConfig = daoConfigMap.get(ContactsBeanDao.class).clone();
        contactsBeanDaoConfig.initIdentityScope(type);

        seachContentDaoConfig = daoConfigMap.get(SeachContentDao.class).clone();
        seachContentDaoConfig.initIdentityScope(type);

        tripBeanDaoConfig = daoConfigMap.get(TripBeanDao.class).clone();
        tripBeanDaoConfig.initIdentityScope(type);

        contactsBeanDao = new ContactsBeanDao(contactsBeanDaoConfig, this);
        seachContentDao = new SeachContentDao(seachContentDaoConfig, this);
        tripBeanDao = new TripBeanDao(tripBeanDaoConfig, this);

        registerDao(ContactsBean.class, contactsBeanDao);
        registerDao(SeachContent.class, seachContentDao);
        registerDao(TripBean.class, tripBeanDao);
    }
    
    public void clear() {
        contactsBeanDaoConfig.clearIdentityScope();
        seachContentDaoConfig.clearIdentityScope();
        tripBeanDaoConfig.clearIdentityScope();
    }

    public ContactsBeanDao getContactsBeanDao() {
        return contactsBeanDao;
    }

    public SeachContentDao getSeachContentDao() {
        return seachContentDao;
    }

    public TripBeanDao getTripBeanDao() {
        return tripBeanDao;
    }

}
